name: run-csv-updater

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main

jobs:
  run-csv-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Debug check secret
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "GCP_SA_KEY secret is NOT set!"
            exit 1
          else
            echo " GCP_SA_KEY secret is detected."
            echo "${{ secrets.GCP_KEY }}" | jq 'keys' || echo "JSON not valid"
          fi

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cs-dashboard-468310

      - name: Run script
        run: |
          python3 your_script.py
