name: Run Poller

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # allow manual trigger

jobs:
  run-poller:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install google-cloud-storage elasticsearch requests

      - name: Write GCP key to file
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ${{ github.workspace }}/gcp-key.json
          jq empty ${{ github.workspace }}/gcp-key.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
          python main.py
