name: Run Poller Every 30 Seconds

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minute (cron doesn't support 30s natively)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run poller (fetch URLs)
        run: |
          python try_new_updates.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          ES_API_KEY_ID: ${{ secrets.ES_API_KEY_ID }}
          ES_API_KEY_SECRET: ${{ secrets.ES_API_KEY_SECRET }}
          ES_ENDPOINT: https://mi-reporting.es.us-west-2.aws.found.io
