name: run-csv-updater

on:
  workflow_dispatch:   # manual trigger for testing
  schedule:            # optional: run every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Write service account key to file
      - name: Write GCP key to file
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ${{ github.workspace }}/gcp-key.json
          jq empty ${{ github.workspace }}/gcp-key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cs-dashboard-468310
          install_components: gsutil

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install google-cloud-storage google-cloud-bigquery elasticsearch requests

      # Step 6: Run your updater script
      - name: Run CSV updater
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
          echo "🚀 Running CSV updater..."
          python main.py

      # Step 7: Upload test file to
