name: Test GCP Secret

on:
  workflow_dispatch:   # run manually from GitHub UI

jobs:
  validate-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Write and validate GCP key
        run: |
          # Write secret to file and fix escaped \n
          echo "${{ secrets.GCP_SA_KEY }}"  > gcp-key.json

          # Show size (should be ~2-3KB)
          echo "File size: $(wc -c < gcp-key.json) bytes"

          # Validate JSON format
          jq empty gcp-key.json

          # Print project ID + client email (safe fields)
          echo "Project ID: $(jq -r .project_id gcp-key.json)"
          echo "Client Email: $(jq -r .client_email gcp-key.json)"
